### ISSUE TITLE
Check how is online on PS4, Xbox, Steam, etc?

### ISSUE THREAD

**Issue by Eivinddh** [arnekva/MazariniBot#12]
> Bare ein ide, men som eg isje tror funke/e veldig vanskelig å implementera:
> 
> Commando typ "!mz online" e.l. som sjekke kem som e online på ps4/xbox/steam osv. Tvile for atte d e mulig / någen API-er for d, men tenkte nå vertfall å posta ideen

**Comment by arnekva** [comment]
Moving
