### ISSUE TITLE
Have a !mz fin klokka command?

### ISSUE THREAD

**Issue by Eivinddh** [arnekva/MazariniBot#7]

**Comment by arnekva** [comment]
Tenke at funksjoner som bare randomly sende meldinger uten å triggast bler for mye spam.

**Comment by Eivinddh** [comment]
Tenkte heller at folk kan skriva !mz fin klokka et par sek før kl. X:00 og at det då enten komme "Nei, nå va du litt for tidlig" eller "Fin klokka"

**Comment by arnekva** [comment]
Moved to https://github.com/arnekva/Mazarini-Bot/issues/5
