### ISSUE TITLE
Check if Magnus is playing games between 08:00 and 16:00

### ISSUE THREAD

**Issue by Eivinddh** [arnekva/MazariniBot#9]
kan ikkje boten lesa av description og hvis det står "playing xx" mellom 08:00 og 16:00 så taggan maggi og skrive: "Koss går det med masteren?"

`maggi = await client.fetch_user(221739293889003520)
if maggi.game == None:
  return
else
 await channel.send("@Deadmaggi, koss går det med masteren?")`

**Comment by arnekva** [comment]
Moved to https://github.com/arnekva/Mazarini-Bot/issues/1
